site_name: NextUI Docs
site_url: https://nextui.loveretro.games
repo_url: https://github.com/LoveRetro/NextUI
edit_uri: https://github.com/LoveRetro/nextui-wiki/edit/main/docs/
repo_name: LoveRetro/NextUI
copyright: © 2025 NextUI Contributors

theme:
  name: material
  custom_dir: marketing/out
  logo: _inc/images/nextui-logo.png
  favicon: _inc/images/favicon.png
  font:
    text: Raleway
    code: Fira Code
  icon:
    admonition:
      warning: octicons/alert-24
      info: octicons/info-24
      example: octicons/sparkles-fill-24
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: nextui-wiki-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nextui-wiki-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

extra_css:
  - _inc/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LoveRetro/NextUI
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HKd7wqZk3h

  urls:
    discord: https://discord.gg/HKd7wqZk3h
    github: https://github.com/LoveRetro/NextUI

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 3
      permalink: 🔗

plugins:
  - search
  - macros

nav:
  - Docs Home: docs.md
  - Usage: usage.md
  - Customizing: customizing.md
  - Paks: paks.md
  - Shaders:
      - shaders/index.md
  - Support:
      - Frequently Asked Questions: support/faq.md
  - Development: development/build.md
  - NextUI Homepage:
      - index.md
